import { mkdtempSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import type { HarnessPlan } from "../src/builder";
import {
	EXAMPLE_SKILL,
	HARNESS_SKILLS,
} from "../src/builder/assemble/harness-templates";

// HARNESS_SKILLS is pure (node fs only), so write it + a skills/ dir to temp
// and exercise the real loader — this doubles as an escaping check and, for
// field Defect C, proves the model-facing skill body no longer carries the
// "edit skills to teach it your workflows" meta-sentence that made 3B models
// try to file_edit the skills dir on a "remember X" goal.
const dir = mkdtempSync(join(tmpdir(), "skills-mod-"));
const modFile = join(dir, "skills.ts");
writeFileSync(modFile, HARNESS_SKILLS);
const skillsDir = mkdtempSync(join(tmpdir(), "skills-dir-"));
writeFileSync(
	join(skillsDir, "verify-before-done.md"),
	EXAMPLE_SKILL({ name: "demoharness" } as HarnessPlan),
);

type Skill = { name: string; description: string; triggers: string[]; body: string };
const S = (await import(modFile)) as {
	loadSkills: (dir?: string) => Promise<Skill[]>;
	matchSkills: (skills: Skill[], goal: string) => Skill[];
	skillsPromptBlock: (skills: Skill[]) => string;
};

const skills = await S.loadSkills(skillsDir);
const verify = skills.find((s) => s.name === "verify-before-done");

describe("EXAMPLE_SKILL — field Defect C", () => {
	it("parses the example skill", () => {
		expect(verify).toBeTruthy();
	});

	it("body does NOT carry the developer-facing meta-sentence into the prompt", () => {
		expect(verify?.body).not.toContain("teach it your workflows");
		expect(verify?.body).not.toContain("edit or add");
		expect(verify?.body).not.toContain("generated by harnage");
		// the attribution lives in a frontmatter comment, never in the body
		expect(verify?.body).not.toContain("demoharness");
	});

	it("keeps the actual verification instruction", () => {
		expect(verify?.body).toContain("run the relevant verification");
		expect(verify?.body).toContain("Never\nclaim success without evidence");
	});

	it("has real triggers so it is no longer always-active", () => {
		expect(verify?.triggers.length).toBeGreaterThan(0);
		// a memory/recall goal must NOT pull in the verify skill (the repro goal)
		expect(S.matchSkills(skills, "remember that my favorite color is teal")).toHaveLength(0);
		// an action goal still gets it
		expect(S.matchSkills(skills, "build a commit-message parser").map((s) => s.name)).toContain(
			"verify-before-done",
		);
	});

	it("never injects the attribution into the assembled system-prompt block", () => {
		const block = S.skillsPromptBlock(skills);
		expect(block).not.toContain("teach it your workflows");
		expect(block).not.toContain("demoharness");
	});
});
